// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arkudplubizhptsnebbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFya3VkcGx1Yml6aHB0c25lYmJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTIxNzcsImV4cCI6MjA2NDk2ODE3N30.B-77ClKXDQX2oWahYgkZroj9jBBZhCQnuuH3B9K9q-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);